kumuluzee:
  name: microservice-statistics
  version: 1.0.0
  env:
    name: dev
  server:
    base-url : http://localhost:8084
    http:
      port: 8084
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  health:
    checks:
      disk-space-health-check:
        threshold: 50000000
      etcd-health-check:
        connection-url: http://192.168.99.100:2379/health
  metrics:
    web-instrumentation:
    - name: statistics-endpoint
      url-pattern: /api/v1/*
      status-codes: 500