apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      labels:
        app: statistics
    spec:
      containers:
      - image: mu2729/streaming-statistics
        name: statistics
        env:
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_SERVER_HTTP_PORT
          value: "8080"
        - name: KUMULUZEE_SERVER_BASE-URL
          value: http://159.122.186.127:32289
        - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
          value: http://etcd:2379/health
        ports:
        - containerPort: 8080
          protocol: TCP
          name: stats-port
        livenessProbe:
          httpGet:
            path: /health
            port: stats-port
          initialDelaySeconds: 30
          periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: statistics
spec:
  type: NodePort
  selector:
    app: statistics
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8080